### ISSUE TITLE
Creates blank cert file

### ISSUE THREAD

**Issue by brandonkal** [davewasmer/devcert#26]
I am using devcert-cli to generate certificates. I noticed that the certutil was not functioning correctly so I tried manually installing nss and messing with flags. It was not editing the hosts file either but I tried doing the following:
```
devcert disable domain.test
rm domain.test*
devcert generate domain.test
```

The command failed. Any `devcert generate domain.test` after that creates an empty domain.test.cert file and a good domain.test.key file.

## Here is the error output. It is difficult to reproduce:
```
Error: Command failed: openssl ca -config "/var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/tmp-49642L24yawif0Cw.tmp" -in "/Users/brandonkal/Library/Application Support/
devcert/domains/domain.test/certificate-signing-request.csr" -out "/Users/brandonkal/Library/Application Support/devcert/domains/domain.test/certificate.
crt" -keyfile "/var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/tmp-4964qJFfjg9lx8l0.tmp" -cert "/var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/tmp-4964FBnVmQfD74bV
.tmp" -days 7000 -batch
Using configuration from /var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/tmp-49642L24yawif0Cw.tmp
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'domain.test'
Certificate is to be certified until Sep 22 18:09:43 2037 GMT (7000 days)
failed to update database
TXT_DB error number 2
    at run (~/.nvm/versions/node/v8.11.2/lib/node_modules/devcert-cli/node_modules/devcert/dist/utils.js:24:28)

    at Object.openssl (~/.nvm/versions/node/v8.11.2/lib/node_modules/devcert-cli/node_modules/devcert/dist/utils.js:14:12)
    at constants_1.withDomainCertificateConfig (~/.nvm/versions/node/v8.11.2/lib/node_modules/devcert-cli/node_modules/devcert/dist/certificates.js:34:25)
    at Object.withDomainCertificateConfig (~/.nvm/versions/node/v8.11.2/lib/node_modules/devcert-cli/node_modules/devcert/dist/constants.js:47:5)
    at certificate_authority_1.withCertificateAuthorityCredentials (~/.nvm/versions/node/v8.11.2/lib/node_modules/devcert-cli/node_modules/devcert/dist/certificates.j
s:33:25)
    at Object.<anonymous> (~/.nvm/versions/node/v8.11.2/lib/node_modules/devcert-cli/node_modules/devcert/dist/certificate-authority.js:89:15)
    at Generator.next (<anonymous>)
    at fulfilled (~/.nvm/versions/node/v8.11.2/lib/node_modules/devcert-cli/node_modules/tslib/tslib.js:104:62)
```

**Comment by chimurai** [comment]
Got the same `TXT_DB error number 2` error...

Fixed it by removing all domains using `devcert`:
`devcert list`
`devcert disable {domain}`

---

Remove all entries from (empty index.txt):
`~/Library/Application Support/devcert/certificate-authority/index.txt`

`index.txt` contains data like:
```
V       370911122619Z           01      unknown /CN=localhost
```

---

`devcert generate localhost` should work again

---

@davewasmer should `devcert disable localhost` remove the entry in `~/Library/Application Support/devcert/certificate-authority/index.txt` ?
