### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by Warix3** [davewasmer/devcert#68]
I'm getting this error:
`[!] (plugin at position 6) Error: spawnSync sh ENOENT
Error: spawnSync sh ENOENT
    at notFoundError (C:\Users\Toni\WebstormProjects\pogoweb-frontend\svelte-app\node_modules\cross-spawn\lib\enoent.js:6:26)
    at Object.verifyENOENTSync (C:\Users\Toni\WebstormProjects\pogoweb-frontend\svelte-app\node_modules\cross-spawn\lib\enoen
t.js:48:16)
    at Function.spawnSync [as sync] (C:\Users\Toni\WebstormProjects\pogoweb-frontend\svelte-app\node_modules\cross-spawn\inde
x.js:29:43)
    at C:\Users\Toni\WebstormProjects\pogoweb-frontend\svelte-app\node_modules\password-prompt\index.js:79:26
    at new Promise (<anonymous>)
    at Object.notty (C:\Users\Toni\WebstormProjects\pogoweb-frontend\svelte-app\node_modules\password-prompt\index.js:76:12)
    at Object.raw (C:\Users\Toni\WebstormProjects\pogoweb-frontend\svelte-app\node_modules\password-prompt\index.js:11:71)
    at Object.mask (C:\Users\Toni\WebstormProjects\pogoweb-frontend\svelte-app\node_modules\password-prompt\index.js:8:37)
    at Object.prompt [as default] (C:\Users\Toni\WebstormProjects\pogoweb-frontend\svelte-app\node_modules\password-prompt\in
dex.js:112:30)
    at Object.<anonymous> (C:\Users\jzetlen\gits\devcert\user-interface.ts:15:32)
`
It's because of the password-prompt module. Please consider replacing it with something that works on windows. I've submitted the issue on their repo too but it looks kinda inactive there.

**Comment by chiefraccoon** [comment]
still doesn't work
